version: 2
updates:
# Maintain dependencies for GitHub Actions
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
    day: "saturday"
    time: "06:00"
    timezone: "America/Toronto"
  reviewers:
    - "jidicula"
  open-pull-requests-limit: 99
  commit-message:
    prefix: "build: "
- package-ecosystem: "gomod"
  directory: "/"
  schedule:
    interval: weekly
    day: "saturday"
    time: "06:00"
    timezone: "America/Toronto"
  reviewers:
    - "jidicula"
  commit-message:
    prefix: "build: "
