repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: mixed-line-ending
      - id: check-added-large-files
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.38.0
    hooks:
      - id: golangci-lint
