on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

name: Build

defaults:
  run:
    shell: bash

jobs:
  lint:
    name: Lint files
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
  test:
    name: Run tests
    runs-on: 'ubuntu-latest'
    needs: lint
    steps:
      - uses: actions/checkout@v2
      - run: go test -v -cover
  build:
    name: Build binary
    runs-on: ${{ matrix.os }}
    needs: test
    strategy:
      matrix:
        os:
          - 'ubuntu-latest'
          - 'macos-latest'
          - 'windows-latest'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get OS info
        run: |
          BINARY_NAME=random-standup-$(echo ${{matrix.os}} | sed 's/-latest//')
          echo "BINARY_NAME=$BINARY_NAME" >> $GITHUB_ENV
      - name: Build
        run: |
          go build -o "$BINARY_NAME" -v
